version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project

jobs:
  test_mouse_recorder:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install and Run
          command: |
            chmod +x scripts/execute/run.sh
            ./scripts/execute/run.sh


workflows:
  version: 2
  test-all:
    jobs:
      - test_mouse_recorder


